#!/usr/bin/env python3

import time
import sys
import argparse
import requests


def main():

    parser = argparse.ArgumentParser()
    parser.add_argument('-u', '--url', type=str, required=True)
    parser.add_argument('-c', '--critical', type=str, required=True)
    parser.add_argument('-w', '--warning', type=str, required=True)
    args = parser.parse_args()

    path = '/recent?pair=BTCUSDT'
    try:
        data = requests.get(args.url + path)
    except Exception as exc:
        sys.stderr.write("Unable to connect: %s" % str(exc))
        sys.exit(3)

    output = data.json()['closeTime']
    epoch = int(int(output)/1000)
    current = int(time.time())

    diff = current - epoch

    if diff > int(args.critical):
        print("CRITICAL - epoch is {} seconds old".format(diff))
        sys.exit(2)
    elif diff > int(args.warning):
        print("WARNING - epoch is {} seconds old".format(diff))
        sys.exit(1)
    else:
        print("OK - epoch is {} seconds old".format(diff))
        sys.exit(0)

if __name__ == '__main__':
    main()
