#! /bin/bash
#
# Author : Diego Martin Gardella [dgardella@gmail.com]
# Modified by Erling Ouweneel to switch OK and CRITICAL
#
# Desc : Plugin to verify if a file does not exist
#
#
PROGNAME=`basename $0`

if [ "$1" = "" ]
then
echo -e " Use : $PROGNAME -- Ex : $PROGNAME /etc/hosts \n "
exit $STATE_UNKNOWN
fi


if [[ -f $1 ]]; then
  echo "CRITICAL : EXISTS :: `ls $@ |tr '\n' ' '`" # shows the first three lines of the file
  exit 2
else
  echo "OK : $1 Does NOT exists "
  exit 0
fi
