#!/usr/bin/env python

import sys
from greencandle.lib.redis_conn import Redis

def main():
    redis = Redis()

    intervals = ['1m', '5m', '1h', '4h', '12h']

    for interval in intervals:
        pair_set = set()
        for item in redis.conn.scan_iter("*:{}".format(interval)):
            pair_set.add(item.decode().split(":")[0])
        pairs = list(pair_set)

        for pair in pairs:
            items = redis.get_items(pair, interval)
            count = set([int(j)-int(i) for i, j in zip(items[:-1], items[1:])])
            if len(count) > 1:
                print("CRITIAL: problem with pair {}: {}".format(pair, count))
                sys.exit(2)
    print("OK")

if __name__ == '__main__':
    main()
