#!/usr/bin/env bash

function usage {
  echo "Container uptime"
  echo "check number of containers running for weeks/months"
  echo "Usage: $0 <warning_count> <critical_count>"
  echo
  echo "eg. ./$0 2 3"
  exit 3
}

warning_count=$1
critical_count=$2

[[ -z "$critical_count" ]] && usage

count=`docker ps --format="{{.Image}} {{.Names}} {{.Status}} "|grep -E 'weeks|months' |awk '$1~/amrox/ {print}'|grep -vE 'nagios|nrpe|cron'|wc -l`

if [[ "$count" -ge "$critical_count" ]]; then
    result=CRITICAL
    exit=2
elif [[ "$count" -ge "$warning_count" ]]; then
    result=WARNING
    exit=1
elif [[ "$count" -lt "$warning_count" ]]; then
    result=OK
    exit=0
else
    result=UNKNOWN
    exit=3
fi

echo "$result $count containers with high uptime|count=$count"
exit $exit
